// <auto-generated />
using System;
using AracIhale.API.MyContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AracIhale.API.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230515232656_four")]
    partial class four
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AracIhale.API.DTO.AracOzellik", b =>
                {
                    b.Property<int>("AracOzellikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AracMarkaID")
                        .HasColumnType("int");

                    b.Property<int?>("AracModelID")
                        .HasColumnType("int");

                    b.Property<int?>("GovdeTipiID")
                        .HasColumnType("int");

                    b.Property<string>("OpsiyonelDonanim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RenkID")
                        .HasColumnType("int");

                    b.Property<string>("Versiyon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VitesTipiID")
                        .HasColumnType("int");

                    b.Property<int?>("YakitTipiID")
                        .HasColumnType("int");

                    b.Property<int?>("YilID")
                        .HasColumnType("int");

                    b.HasKey("AracOzellikID");

                    b.ToTable("AracOzelliks");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Araclar", b =>
                {
                    b.Property<int>("AracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AracFiyati")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AracOzellikID")
                        .HasColumnType("int");

                    b.Property<int?>("BireyselKurumsalID")
                        .HasColumnType("int");

                    b.Property<string>("Donanim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Gorsel1")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("Gorsel2")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("Gorsel3")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("Gorsel4")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("Gorsel5")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<string>("KMBilgisi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("KurumsalSirketAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plaka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StatuID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("AracID");

                    b.HasIndex("AracOzellikID");

                    b.HasIndex("BireyselKurumsalID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Araclars");
                });

            modelBuilder.Entity("AracIhale.API.DTO.BireyselKurumsal", b =>
                {
                    b.Property<int>("BireselKurumsalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Durum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BireselKurumsalID");

                    b.ToTable("BireyselKurumsal");
                });

            modelBuilder.Entity("AracIhale.API.DTO.IhaleListesi", b =>
                {
                    b.Property<int>("IhaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AracID")
                        .HasColumnType("int");

                    b.Property<int?>("AracOzellikID")
                        .HasColumnType("int");

                    b.Property<int?>("AraclarAracID")
                        .HasColumnType("int");

                    b.Property<int?>("BireyselKurumsalID")
                        .HasColumnType("int");

                    b.Property<string>("IhaleAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IhaleBaslangicFiyati")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IhaleBaslangicSaati")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IhaleBaslangicTarihi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IhaleBitisSaati")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IhaleBitisTarihi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IhaleStatuID")
                        .HasColumnType("int");

                    b.Property<string>("KurumsalSirketAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MinimumAlimFiyati")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IhaleID");

                    b.HasIndex("AracOzellikID");

                    b.HasIndex("AraclarAracID");

                    b.HasIndex("BireyselKurumsalID");

                    b.ToTable("IhaleListesi");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AktifPasifID")
                        .HasColumnType("int");

                    b.Property<int?>("BireyselKurumsalID")
                        .HasColumnType("int");

                    b.Property<string>("FirmaAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FirmaBilgisiID")
                        .HasColumnType("int");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KurumsalAdres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("KurumsalIl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KurumsalIlce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("BireyselKurumsalID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RolAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Araclar", b =>
                {
                    b.HasOne("AracIhale.API.DTO.AracOzellik", "AracOzellik")
                        .WithMany("Araclars")
                        .HasForeignKey("AracOzellikID");

                    b.HasOne("AracIhale.API.DTO.BireyselKurumsal", "BireyselKurumsal")
                        .WithMany("Araclars")
                        .HasForeignKey("BireyselKurumsalID");

                    b.HasOne("AracIhale.API.DTO.Kullanici", "Kullanici")
                        .WithMany("Araclars")
                        .HasForeignKey("KullaniciID");

                    b.Navigation("AracOzellik");

                    b.Navigation("BireyselKurumsal");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AracIhale.API.DTO.IhaleListesi", b =>
                {
                    b.HasOne("AracIhale.API.DTO.AracOzellik", null)
                        .WithMany("IhaleListesis")
                        .HasForeignKey("AracOzellikID");

                    b.HasOne("AracIhale.API.DTO.Araclar", null)
                        .WithMany("IhaleListesis")
                        .HasForeignKey("AraclarAracID");

                    b.HasOne("AracIhale.API.DTO.BireyselKurumsal", null)
                        .WithMany("IhaleListesis")
                        .HasForeignKey("BireyselKurumsalID");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Kullanici", b =>
                {
                    b.HasOne("AracIhale.API.DTO.BireyselKurumsal", "BireyselKurumsal")
                        .WithMany("Kullanicis")
                        .HasForeignKey("BireyselKurumsalID");

                    b.HasOne("AracIhale.API.DTO.Rol", null)
                        .WithMany("Kullanicis")
                        .HasForeignKey("RolID");

                    b.Navigation("BireyselKurumsal");
                });

            modelBuilder.Entity("AracIhale.API.DTO.AracOzellik", b =>
                {
                    b.Navigation("Araclars");

                    b.Navigation("IhaleListesis");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Araclar", b =>
                {
                    b.Navigation("IhaleListesis");
                });

            modelBuilder.Entity("AracIhale.API.DTO.BireyselKurumsal", b =>
                {
                    b.Navigation("Araclars");

                    b.Navigation("IhaleListesis");

                    b.Navigation("Kullanicis");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Kullanici", b =>
                {
                    b.Navigation("Araclars");
                });

            modelBuilder.Entity("AracIhale.API.DTO.Rol", b =>
                {
                    b.Navigation("Kullanicis");
                });
#pragma warning restore 612, 618
        }
    }
}
